spring.application.name=employee-management
spring.datasource.url=jdbc:postgresql://localhost:5432/ems
spring.datasource.username=postgres
spring.datasource.password=aditya



spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

jwt.secret=9vK3mX7pQ2rN8tY5uL1wE6cA4sD0fH9jZ8bV3nM5kP2xR7qW
jwt.expiration=3600000

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.instance.prefer-ip-address=true
