spring.application.name=employee-management
spring.datasource.url=jdbc:postgresql://localhost:5432/ems
spring.datasource.username=postgres
spring.datasource.password=aditya



spring.jpa.hibernate.ddl-auto=update


